version: '3.8'

# ❗ NOTES: 
#   1. With NUXT server-side runtime envs you need to add NUXT_
#      - eg. NUXT_OPENAI_API_KEY=xyz (✓)
#      - eg. OPENAI_API_KEY=xyz      (✗)
#   
#   2. While using URLs, be careful with extra qoutes
#      - eg. NUXT_API_ENDPOINT=http://localhost:3000/api/v1/prediction/6fac0499-e1bf-498f-a07d-89d52d8ac209   (✓)
#      - eg. NUXT_API_ENDPOINT='http://localhost:3000/api/v1/prediction/6fac0499-e1bf-498f-a07d-89d52d8ac209' (✗)

services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: docker.io/jeetmetapercept/quizzee:latest
    ports:
      - "80:3000"
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - PROJECT_NAME=Nuxt-Starter-Kit
