username: AI Flow Mapper Workflow
icon_url: https://ai-flow-mapper.netlify.app/_nuxt/logo.ivqId8di.png

text: |
  *Environment: `{{ref}}`*
  *Job: `{{jobName}}`*
  *Status: `{{jobStatus}}`*
  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
  {{#if payload.commits}}
  *Commits*
  {{#each payload.commits}}
  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
  {{/each}}
  {{/if}}

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Workflow
    value: '<{{workflowUrl}}|{{workflow}}>'
    short: true
  - title: Git Ref
    value: '{{ref}} ({{refType}})'
    short: true
  - title: Run ID
    value: |-
      <{{workflowRunUrl}}|{{runId}}>
    short: true
  - title: Run Number
    value: '{{runNumber}}'
    short: true
  - title: Actor
    value: '{{actor}}'
    short: true
  - title: Job Status
    value: '{{jobStatus}}'
    short: true

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: good
  failure: danger
  cancelled: warning
  default: '#439FE0'

icons:
  success: ':check-verified:'
  failure: ':x:'
  cancelled: ':warning:'
  skipped: ':heavy_minus_sign:'
  default: ':question:'
