name: Vercel workflow
on:
  push:
    branches:
      - preview
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code  ...
        uses: actions/checkout@v2
 
      - name: Setup Node 18 ...
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies with pnpm
        run: pnpm install

      - name: Build the project with pnpm
        run: pnpm build

      - name: Deploy to Vercel ...
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          args: deploy --prod 
